### ISSUE TITLE
Auto clear finished error

### ISSUE THREAD

**Issue by PsychoSid** [death-claw/vripper-project#120]
Hi,

Thanks for the continuing work. Seeing this quite a bit currently with a build from the latest commit to main

```2023-09-05T08:13:17.533+01:00 ERROR 65674 --- [pool-4-thread-4] ErrorHandler                             : Uncaught error

java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-4-thread-4
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:294)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:475)
	at javafx.scene.Parent$3.onProposedChange(Parent.java:475)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:289)
	at javafx.scene.control.skin.LabeledSkinBase.lambda$new$11(LabeledSkinBase.java:219)
...
```

Not the full trace but generally fires when a download of a message has completed.

**Comment by death-claw** [comment]
Can you please post the complete stacktrace ?

**Comment by PsychoSid** [comment]
Sorry, sure 

```
ava.lang.IllegalStateException: Not on FX application thread; currentThread = pool-4-thread-11
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:294)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:475)
	at javafx.scene.Parent$3.onProposedChange(Parent.java:475)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:289)
	at javafx.scene.control.skin.LabeledSkinBase.lambda$new$11(LabeledSkinBase.java:219)
	at com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:88)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:50)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:71)
	at javafx.scene.control.Labeled.setText(Labeled.java:147)
	at javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin.lambda$new$2(TabPaneSkin.java:1441)
	at com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:88)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
	at javafx.beans.property.StringPropertyBase$Listener.invalidated(StringPropertyBase.java:231)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
	at javafx.beans.property.StringPropertyBase$Listener.invalidated(StringPropertyBase.java:231)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:187)
	at com.sun.javafx.binding.Subscription.lambda$subscribeInvalidations$4(Subscription.java:116)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.binding.IntegerBinding.invalidate(IntegerBinding.java:182)
	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:319)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:71)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:238)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:210)
	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:190)
	at java.base/java.util.AbstractList$Itr.remove(AbstractList.java:389)
	at java.base/java.util.Collection.removeIf(Collection.java:577)
	at me.mnlr.vripper.view.tables.PostsTableView$5.invoke(PostsTableView.kt:63)
	at me.mnlr.vripper.view.tables.PostsTableView$5.invoke(PostsTableView.kt:62)
	at me.mnlr.vripper.view.tables.PostsTableView._init_$lambda$4(PostsTableView.kt:62)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113)
	at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:471)
	at reactor.core.publisher.SinkManyEmitterProcessor.tryEmitNext(SinkManyEmitterProcessor.java:269)
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
	at me.mnlr.vripper.event.EventBus.publishEvent(EventBus.kt:15)
	at me.mnlr.vripper.repositories.impl.PostDownloadStateRepositoryImpl.deleteByPostId(PostDownloadStateRepositoryImpl.kt:108)
	at me.mnlr.vripper.services.DataTransaction.remove(DataTransaction.kt:109)
	at me.mnlr.vripper.services.DataTransaction.finishPost(DataTransaction.kt:99)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at me.mnlr.vripper.services.DataTransaction$$SpringCGLIB$$0.finishPost(<generated>)
	at me.mnlr.vripper.download.DownloadService.afterJobFinish(DownloadService.kt:277)
	at me.mnlr.vripper.download.DownloadService.schedule$lambda$28$lambda$27(DownloadService.kt:260)
	at net.jodah.failsafe.internal.EventListener.lambda$of$0(EventListener.java:37)
	at net.jodah.failsafe.FailsafeExecutor.handleComplete(FailsafeExecutor.java:322)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:130)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:212)
	at me.mnlr.vripper.download.DownloadService.schedule$lambda$28(DownloadService.kt:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by death-claw** [comment]
I am able to reproduce, thanks for reporting
