### ISSUE TITLE
[Error] Error when finishing package

### ISSUE THREAD

**Issue by madrooky** [death-claw/vripper-project#132]
This error pops up very often when a package is finished. Program needs to be restarted after that.
Let me know if you need more details from the log. I just started to use this program and don't much about it yet.

Error in java.base/java.util.AbstractList$Itr.checkForComodification(Unknown Source)
```
java.util.ConcurrentModificationException
	at java.base/java.util.AbstractList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.AbstractList$Itr.next(Unknown Source)
	at me.mnlr.vripper.gui.view.tables.PostsTableView$onDock$1$5$1$1.invokeSuspend(PostsTableView.kt:78)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: java.util.ConcurrentModificationException
		... 9 more
	Suppressed: java.util.ConcurrentModificationException
		... 9 more
	Suppressed: java.util.ConcurrentModificationException
		... 9 more
	Suppressed: java.util.ConcurrentModificationException
		... 9 more
	Suppressed: java.util.ConcurrentModificationException
		... 9 more
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@389d8e7a, Dispatchers.Default]
```

**Comment by madrooky** [comment]
Little addition, the program is still working after the Error, but it wont update the main window and all the elements. I can still start other downloads and see on the bottom panel the process.

**Comment by madrooky** [comment]
Got a workaround. Don't check to clear finished downloads.

**Comment by death-claw** [comment]
What version are you using ?

**Comment by madrooky** [comment]
> What version are you using ?

5.0.0

What I learned in the meantime is that sometimes the app can't load the thumbnails which then leads to errors and the UI not updating any more. It is still working then but to update the UI the app has to be restarted. The status bar at the bottom is still working when this happens. Currently I can't provide an example.

**Comment by madrooky** [comment]
> What version are you using ?

Ok i tested the latest version and clean up finished is not causing errors any more. Thanks.
