### ISSUE TITLE
5.5.0 Error when adding multiple links

### ISSUE THREAD

**Issue by madrooky** [death-claw/vripper-project#179]
Happens when adding multiple links via clipboard. Links extracted from the search list with a browser plugin and a filter. So its only links from the post and not random links to other posts.

My first assumption is it has to do with posts that don't have any working link, because I had a kinda similar issue with the 5.0 version only that the error came up when deleting such links in batch after all (working) downloads were finished.

I have just downloaded the new version and will try to provide better details once the picture gets more clear, if necessary.

![image](https://github.com/death-claw/vripper-project/assets/131664307/237c30f0-4a75-49d5-bde7-e376c8577ae5)

`org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Eindeutiger Index oder Primärschlüssel verletzt: "PUBLIC.CONSTRAINT_INDEX_1 ON PUBLIC.METADATA(POST_ID NULLS FIRST) VALUES ( /* 4 */ CAST(70900039 AS BIGINT) )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_1 ON PUBLIC.METADATA(POST_ID NULLS FIRST) VALUES ( /* 4 */ CAST(70900039 AS BIGINT) )"; SQL statement:
INSERT INTO METADATA ("DATA", POST_ID) VALUES (?, ?) [23505-224]
SQL: [INSERT INTO METADATA ("DATA", POST_ID) VALUES (?, ?)]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:94)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:248)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:225)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:55)
	at org.jetbrains.exposed.sql.QueriesKt.insert(Queries.kt:144)
	at me.vripper.repositories.impl.MetadataRepositoryImpl.save(MetadataRepositoryImpl.kt:20)
	at me.vripper.services.DataTransaction$saveMetadata$1.invoke(DataTransaction.kt:214)
	at me.vripper.services.DataTransaction$saveMetadata$1.invoke(DataTransaction.kt:214)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:306)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:353)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:361)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:352)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:261)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:361)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:231)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:209)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:208)
	at me.vripper.services.DataTransaction.saveMetadata(DataTransaction.kt:214)
	at me.vripper.services.MetadataService$fetchMetadata$1.invokeSuspend(MetadataService.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@4a2a7e7, Dispatchers.IO]
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Eindeutiger Index oder Primärschlüssel verletzt: "PUBLIC.CONSTRAINT_INDEX_1 ON PUBLIC.METADATA(POST_ID NULLS FIRST) VALUES ( /* 4 */ CAST(70900039 AS BIGINT) )"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_1 ON PUBLIC.METADATA(POST_ID NULLS FIRST) VALUES ( /* 4 */ CAST(70900039 AS BIGINT) )"; SQL statement:
INSERT INTO METADATA ("DATA", POST_ID) VALUES (?, ?) [23505-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:520)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:527)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:256)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:216)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:174)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:55)
	at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:158)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:168)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:18)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:92)
	... 27 more
`

![image](https://github.com/death-claw/vripper-project/assets/131664307/2fffdaec-eaa1-433f-b6c5-e2488b2de83b)

**Comment by madrooky** [comment]
Perhaps related, another error might happen when trying to open a thread on the thread tab that does not contain downloadable content, however that ends up there in the first place.

In this case I did not get an error when adding a list of links, but one link was added to the threads but could not be opened.

![image](https://github.com/death-claw/vripper-project/assets/131664307/a9810cfa-92eb-4032-a422-ce5e11a1f26c)

`me.vripper.exception.PostParseException: Failed to get links for threadId = 5550295, Unable to find links for threadId = 5550295
	at me.vripper.services.AppEndpointService.grab(AppEndpointService.kt:153)
	at me.vripper.gui.controller.ThreadController.grab(ThreadController.kt:42)
	at me.vripper.gui.components.fragments.ThreadSelectionTableFragment$onDock$1$list$1.invokeSuspend(ThreadSelectionTableFragment.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@1ec26ce9, Dispatchers.IO]`

**Comment by madrooky** [comment]
Forgot to mention:
-> portable version for windows.

Would there be a difference using one with installer?

**Comment by madrooky** [comment]
The second error happens when a thread only shows one count in the list.
Every thread that has count >2 is fine.

![image](https://github.com/death-claw/vripper-project/assets/131664307/b75d2ac0-ef75-446d-9356-0391f6c9e697)

**Comment by death-claw** [comment]
Was there some duplicate links that you added ?

**Comment by madrooky** [comment]
Yes, when I filter a list with the link extractor with the filter "/threads" i get that kind of list that causes errors to pop up:

`https://vipergirls.to/threads/10496282-Marie-Set-C3-x42-3000px-(Mar-16-2015)
https://vipergirls.to/threads/10496282-Marie-Set-C3-x42-3000px-(Mar-16-2015)?p=173545819#post173545819
https://vipergirls.to/threads/10496293-Marie-Set-C3BW-x42-3000px-(Mar-15-2015)
https://vipergirls.to/threads/10496293-Marie-Set-C3BW-x42-3000px-(Mar-15-2015)?p=173545989#post173545989
https://vipergirls.to/threads/10496305-Marie-Set-C4-x45-3000px-(Apr-13-2015)
https://vipergirls.to/threads/10496305-Marie-Set-C4-x45-3000px-(Apr-13-2015)?p=173546209#post173546209
https://vipergirls.to/threads/10496318-Marie-Set-C5-x48-3000px-(Sep-14-2016)
https://vipergirls.to/threads/10496318-Marie-Set-C5-x48-3000px-(Sep-14-2016)?p=173546440#post173546440
https://vipergirls.to/threads/10496332-Marie-Set-C6-x51-3000px-(Nov-13-2016)
https://vipergirls.to/threads/10496332-Marie-Set-C6-x51-3000px-(Nov-13-2016)?p=173546644#post173546644
https://vipergirls.to/threads/10496342-Marie-Set-C6BW-x39-3000px-(Nov-14-2016)
https://vipergirls.to/threads/10496342-Marie-Set-C6BW-x39-3000px-(Nov-14-2016)?p=173546804#post173546804
https://vipergirls.to/threads/10496351-Marie-Set-C8-x39-3000px-(Aug-13-2019)
https://vipergirls.to/threads/10496351-Marie-Set-C8-x39-3000px-(Aug-13-2019)?p=173546951#post173546951
https://vipergirls.to/threads/10496361-Marie-Set-C9-x33-3000px-(Oct-14-2019)
https://vipergirls.to/threads/10496361-Marie-Set-C9-x33-3000px-(Oct-14-2019)?p=173547097#post173547097
https://vipergirls.to/threads/10497466-Bella-Mirror-Game-x100-5040px-Jan-20-2024
https://vipergirls.to/threads/10497466-Bella-Mirror-Game-x100-5040px-Jan-20-2024?p=173562915#post173562915
https://vipergirls.to/threads/10498018-13-04-2024-Diana-243-180-pics-260-MB
https://vipergirls.to/threads/10498018-13-04-2024-Diana-243-180-pics-260-MB?goto=newpost
https://vipergirls.to/threads/10498018-13-04-2024-Diana-243-180-pics-260-MB?p=173865687#post173865687
https://vipergirls.to/threads/10498446-Jessica-B-10608-95-pics-6700px-14-April-2024
https://vipergirls.to/threads/10498446-Jessica-B-10608-95-pics-6700px-14-April-2024?p=173577011#post173577011
https://vipergirls.to/threads/10500274-Onlydi-Set-592-x21-5617px-04-14-2024
https://vipergirls.to/threads/10500274-Onlydi-Set-592-x21-5617px-04-14-2024?p=173604491#post173604491
https://vipergirls.to/threads/10500908-27-03-2024-Brigi-Budai-Sea-Breeze-56-pics-98-MB
https://vipergirls.to/threads/10500908-27-03-2024-Brigi-Budai-Sea-Breeze-56-pics-98-MB?p=173618726#post173618726
https://vipergirls.to/threads/10500916-29-03-2024-Zurine-Aspiunza-Ibiza-Vibes-78-pics-120-MB
https://vipergirls.to/threads/10500916-29-03-2024-Zurine-Aspiunza-Ibiza-Vibes-78-pics-120-MB?goto=newpost
https://vipergirls.to/threads/10500916-29-03-2024-Zurine-Aspiunza-Ibiza-Vibes-78-pics-120-MB?p=173632878#post173632878
https://vipergirls.to/threads/10501242-Minnie-Lighter-Take-It-Off-109-pictures-8192px-(14-Apr-2024)
https://vipergirls.to/threads/10501242-Minnie-Lighter-Take-It-Off-109-pictures-8192px-(14-Apr-2024)?goto=newpost
https://vipergirls.to/threads/10501242-Minnie-Lighter-Take-It-Off-109-pictures-8192px-(14-Apr-2024)?p=173628356#post173628356
https://vipergirls.to/threads/10501245-Kiana-Presenting-Kiana-61-pictures-(04-14-2024)
https://vipergirls.to/threads/10501245-Kiana-Presenting-Kiana-61-pictures-(04-14-2024)?goto=newpost
https://vipergirls.to/threads/10501245-Kiana-Presenting-Kiana-61-pictures-(04-14-2024)?p=173644807#post173644807
https://vipergirls.to/threads/10501247-Tisha-Favorite-Hobby-x138-(04-14-24)
https://vipergirls.to/threads/10501247-Tisha-Favorite-Hobby-x138-(04-14-24)?goto=newpost
https://vipergirls.to/threads/10501247-Tisha-Favorite-Hobby-x138-(04-14-24)?p=173628365#post173628365
https://vipergirls.to/threads/10501249-Selva-Lapiedra-Furry-Fun-x122-(04-14-24)
https://vipergirls.to/threads/10501249-Selva-Lapiedra-Furry-Fun-x122-(04-14-24)?goto=newpost
https://vipergirls.to/threads/10501249-Selva-Lapiedra-Furry-Fun-x122-(04-14-24)?p=173628376#post173628376
https://vipergirls.to/threads/10501255-Macarena-J-Luggage-107-pictures-(04-14-2024)
https://vipergirls.to/threads/10501255-Macarena-J-Luggage-107-pictures-(04-14-2024)?p=173626735#post173626735
https://vipergirls.to/threads/10501257-Aileen-K-Picking-Up-Dandelion-143-pictures-(04-14-2024)
https://vipergirls.to/threads/10501257-Aileen-K-Picking-Up-Dandelion-143-pictures-(04-14-2024)?goto=newpost
https://vipergirls.to/threads/10501257-Aileen-K-Picking-Up-Dandelion-143-pictures-(04-14-2024)?p=173626795#post173626795
https://vipergirls.to/threads/10501284-Meli-New-Beauty-x144-(04-14-24)
https://vipergirls.to/threads/10501284-Meli-New-Beauty-x144-(04-14-24)?goto=newpost
https://vipergirls.to/threads/10501284-Meli-New-Beauty-x144-(04-14-24)?p=173682216#post173682216
https://vipergirls.to/threads/10501900-Mariana-Gotham-x198-(04-14-24)
https://vipergirls.to/threads/10501900-Mariana-Gotham-x198-(04-14-24)?goto=newpost
https://vipergirls.to/threads/10501900-Mariana-Gotham-x198-(04-14-24)?p=173702926#post173702926
https://vipergirls.to/threads/10502034-OnlyFans-Requests-013-Part-2-Filled
https://vipergirls.to/threads/10502054-OnlyFans-Requests-014
https://vipergirls.to/threads/10502761-Anabel-The-Rock-2-(14-04-2024)
https://vipergirls.to/threads/10502761-Anabel-The-Rock-2-(14-04-2024)?goto=newpost
https://vipergirls.to/threads/10502761-Anabel-The-Rock-2-(14-04-2024)?p=173651240#post173651240
https://vipergirls.to/threads/10503901-Katya-C-Antonio-Clemens-Armchair-2024-04-01-x139
https://vipergirls.to/threads/10503901-Katya-C-Antonio-Clemens-Armchair-2024-04-01-x139?goto=newpost
https://vipergirls.to/threads/10503901-Katya-C-Antonio-Clemens-Armchair-2024-04-01-x139?p=173670022#post173670022
https://vipergirls.to/threads/10504686-Foxy-S-Antonio-Clemens-Splash-Water-2024-03-25-x140
https://vipergirls.to/threads/10504686-Foxy-S-Antonio-Clemens-Splash-Water-2024-03-25-x140?goto=newpost
https://vipergirls.to/threads/10504686-Foxy-S-Antonio-Clemens-Splash-Water-2024-03-25-x140?p=173682758#post173682758
https://vipergirls.to/threads/10520121-Mila-I-Temiz-2912x4368px-120x-January-02-2012?goto=newpost
https://vipergirls.to/threads/10520121-Mila-I-Temiz-2912x4368px-120x-January-02-2012?p=173924198#post173924198
https://vipergirls.to/threads/1572540-Guidelines-amp-Rules-Artistic-Photo-Sets
https://vipergirls.to/threads/1572540-Guidelines-amp-Rules-Artistic-Photo-Sets?p=13692808#post13692808`


Using the filter "?p=" causes much less errors as it only refers to replies in a thread not the thread itself, but can still have duplicates in some cases, depending on the thread of course. However not every duplicate causes an error, I have less than 10 per such a list of links of 25 threads.

**Comment by death-claw** [comment]
The app is not handling the duplicates correctly, I can try to restrict the duplicates but that may impact performance when adding a long list of posts, or allow having duplicates but will take some effort because I am assuming that there's no duplicates in different parts of the app.
I'll do more testing before deciding, but thanks for reporting

**Comment by madrooky** [comment]
> The app is not handling the duplicates correctly, I can try to restrict the duplicates but that may impact performance when adding a long list of posts, or allow having duplicates but will take some effort because I am assuming that there's no duplicates in different parts of the app. I'll do more testing before deciding, but thanks for reporting

I thank you for the effort making this nice tool. 

Normally I use jdownloader, it has a deep scan function. But in this scenario it is over the top and would scrape half the the site for links as many posters add links to their own libraries which then likely refer to even more downloadable content^^ 
Might be that a simpler way to circumvent dupes would be to allow to scan the threads from one level higher, but not more. Which would also make it possible to add more links much easier, by creating a list of links referring to pages and simply increase the page page number in this list. That's how I do that with jdownloader and the list can be created easily with VSC or notepad++.
The link extractor I use in this scenario has its limits, one filter does not really add all of the links from one search page and the other has the dupes.
