### ISSUE TITLE
5.5.0 Error when deleting some entires

### ISSUE THREAD

**Issue by madrooky** [death-claw/vripper-project#181]
Deleting some entries that could not download at all or just not finish due to some missing links might results in an error.

![image](https://github.com/death-claw/vripper-project/assets/131664307/372491be-f5ff-42dc-b0c2-7817b9b3591f)

```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at me.vripper.services.AppEndpointService.findPost(AppEndpointService.kt:247)
	at me.vripper.gui.controller.PostController.find(PostController.kt:51)
	at me.vripper.gui.components.views.PostInfoView$setPostId$3$model$1.invokeSuspend(PostInfoView.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@55113f6b, Dispatchers.Default]
```

**Comment by death-claw** [comment]
Can you share come post links that are causing this issue ?

**Comment by madrooky** [comment]
Will try. The issue is that I add links in batches, and when the error happens i have no option to see what link exactly caused the error as it is gone afterwards. 
But you can try with links from WowGirls, there are a lot down. You get errors as I posted in the other report when adding the links and some when deleting. 
I use the "Link Extractor" addon with Firefox to get the list of thread links directly from the search window. Also using the filter "/threads" or "?p=" to prevent the clutter. You can try it and see if you can reproduce the issue simply by searching for threads with "WowGirls" in the title and add the links from the first few result pages.

**Comment by death-claw** [comment]
This is most likely related to #179, the app is written to not allow duplicates, so when there's duplicated posts it just don't know what to do with it.

**Comment by madrooky** [comment]
> This is most likely related to #179, the app is written to not allow duplicates, so when there's duplicated posts it just don't know what to do with it.

Yes it seems that is correct. It does not happen too often, and the issue only appears if the thread cannot be downloaded and removed automatically. When both are selected and deleted at once the error comes up. Deleting one of the duplicates removes both.
