### ISSUE TITLE
Bug in MacOS v14.4.1

### ISSUE THREAD

**Issue by CoditMarks** [death-claw/vripper-project#192]
![ErrorCode in MacOS 14 4 1](https://github.com/death-claw/vripper-project/assets/168951990/cb2ff965-9ab4-4004-8ed7-676d7a983fa5)

java.lang.StringIndexOutOfBoundsException: Range [113, 114) out of bounds for length 113
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at com.sun.glass.ui.mac.MacAccessible.accessibilityAttributeValueForParameter(MacAccessible.java:1844)

Error code after pasting URL's in Add links

**Comment by CoditMarks** [comment]
It is persistent dialog box. Need to force quit current application. Can you please advise how to fix this error / fix it within the code.
