### ISSUE TITLE
V6.0.0 - Clear finished posts doesn't work

### ISSUE THREAD

**Issue by Le-zOU** [death-claw/vripper-project#204]
V6.0.0
Windows portable

pressing the _clear finished post_ button has no effect
![Screenshot 2024-12-16 090525](https://github.com/user-attachments/assets/bd46fa46-74fb-4f9a-954b-9be58fe16bfc)

Thread Thread[#88,DefaultDispatcher-worker-9,5,main] threw an exception
------------
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at me.vripper.services.DataTransaction.finishPost(DataTransaction.kt:160)
	at me.vripper.services.DataTransaction.finishPost$default(DataTransaction.kt:159)
	at me.vripper.download.DownloadService.stopInternal(DownloadService.kt:191)
	at me.vripper.download.DownloadService.stop(DownloadService.kt:76)
	at me.vripper.services.AppEndpointService.remove(AppEndpointService.kt:103)
	at me.vripper.gui.controller.PostController.delete(PostController.kt:35)
	at me.vripper.gui.components.views.PostsTableView$deleteSelected$1$1.invokeSuspend(PostsTableView.kt:501)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)

**Comment by Le-zOU** [comment]
selecting all threads, right click delete has no effect
![Screenshot 2024-12-16 090642](https://github.com/user-attachments/assets/9b1d8e39-0108-416d-88a0-895bbd9d215a)
