### ISSUE TITLE
Frontend (?) not building in (very) clean machine

### ISSUE THREAD

**Issue by vrb-clean** [death-claw/vripper-project#45]
I setup a new virtual machine with Debian 11, and all I installed apart from the base system is: openssh-server (so I can connect to this machine), sudo (so I can administrate it), maven (because it was named as a dependency of this) and wget (to download the zip with this). But when I try to build this with `mvn clean install -Pelectron -DskipTests`, I get (something ending with):
```
[INFO] --- frontend-maven-plugin:1.11.2:yarn (yarn run build) @ vripper-electron ---
[INFO] Running 'yarn run dist' in /home/grove/vripper-project-master/vripper-electron/build-dir
[INFO] yarn run v1.22.10
[INFO] $ node pre-build.js && electron-builder
[INFO] Building runtime environment
[INFO] /bin/sh: 1: jlink: not found
[INFO] child_process.js:655
[INFO]     throw err;
[INFO]     ^
[INFO] 
[INFO] Error: Command failed: jlink --no-header-files --no-man-pages --compress=2 --strip-debug --add-modules java.base,java.desktop,java.instrument,java.management,java.security.jgss,java.sql,jdk.unsupported,jdk.crypto.ec --output java-runtime
[INFO] /bin/sh: 1: jlink: not found
[INFO] 
[INFO]     at checkExecSyncError (child_process.js:616:11)
[INFO]     at execSync (child_process.js:652:15)
[INFO]     at Object.<anonymous> (/home/grove/vripper-project-master/vripper-electron/pre-build.js:21:1)
[INFO]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[INFO]     at Module.load (internal/modules/cjs/loader.js:928:32)
[INFO]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[INFO]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[INFO]     at internal/main/run_main_module.js:17:47 {
[INFO]   status: 127,
[INFO]   signal: null,
[INFO]   output: [
[INFO]     null,
[INFO]     Buffer(0) [Uint8Array] [],
[INFO]     Buffer(29) [Uint8Array] [
[INFO]        47,  98, 105, 110,  47, 115, 104,
[INFO]        58,  32,  49,  58,  32, 106, 108,
[INFO]       105, 110, 107,  58,  32, 110, 111,
[INFO]       116,  32, 102, 111, 117, 110, 100,
[INFO]        10
[INFO]     ]
[INFO]   ],
[INFO]   pid: 590,
[INFO]   stdout: Buffer(0) [Uint8Array] [],
[INFO]   stderr: Buffer(29) [Uint8Array] [
[INFO]      47,  98, 105, 110,  47, 115, 104,
[INFO]      58,  32,  49,  58,  32, 106, 108,
[INFO]     105, 110, 107,  58,  32, 110, 111,
[INFO]     116,  32, 102, 111, 117, 110, 100,
[INFO]      10
[INFO]   ]
[INFO] }
[INFO] error Command failed with exit code 1.
[INFO] error Command failed with exit code 1.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for vripper 3.5.4:
[INFO] 
[INFO] vripper ............................................ SUCCESS [  4.629 s]
[INFO] vripper-ui ......................................... SUCCESS [05:19 min]
[INFO] vripper-server ..................................... SUCCESS [ 24.832 s]
[INFO] vripper-electron ................................... FAILURE [ 21.877 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:14 min
[INFO] Finished at: 2021-12-20T18:13:33Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.2:yarn (yarn run build) on project vripper-electron: Failed to run task: 'yarn run dist' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :vripper-electron
```

If this is just another dependency, please make sure to document it.

**Comment by RsX88** [comment]
You're missing the path %JAVA_HOME%\bin in system variable %PATH

> [INFO] Error: Command failed: jlink --no-header-files --no-man-pages --compress=2 --strip-debug --add-modules java.base,java.desktop,java.instrument,java.management,java.security.jgss,java.sql,jdk.unsupported,jdk.crypto.ec --output java-runtime
> [INFO] /bin/sh: 1: jlink: not found
