### ISSUE TITLE
all pixxxels.cc downloads fail

### ISSUE THREAD

**Issue by Le-zOU** [death-claw/vripper-project#50]
Message
Failed to download https://i.pixxxels.cc/wjj4fyQT/bre-blu-3-3000-033.jpg
 tn.mnlr.vripper.exception.DownloadException: tn.mnlr.vripper.exception.HostException: Unexpected error occurred
	at tn.mnlr.vripper.download.DownloadJob.download(DownloadJob.java:172)
	at tn.mnlr.vripper.download.DownloadJob.run(DownloadJob.java:253)
	at net.jodah.failsafe.Functions.lambda$supplierOf$12(Functions.java:296)
	at net.jodah.failsafe.Functions.lambda$resultSupplierOf$11(Functions.java:283)
	at net.jodah.failsafe.internal.executor.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:67)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:117)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:319)
	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:219)
	at tn.mnlr.vripper.download.DownloadJobWrapper.run(DownloadJobWrapper.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: tn.mnlr.vripper.exception.HostException: Unexpected error occurred
	at tn.mnlr.vripper.host.PixxxelsHost.getNameAndUrl(PixxxelsHost.java:69)
	at tn.mnlr.vripper.download.DownloadJob.download(DownloadJob.java:101)
	... 11 more
Caused by: java.lang.NullPointerException
	at tn.mnlr.vripper.host.PixxxelsHost.getNameAndUrl(PixxxelsHost.java:63)
	... 12 more

**Comment by Le-zOU** [comment]
[vripper.log](https://github.com/death-claw/vripper-project/files/8031652/vripper.log)

**Comment by death-claw** [comment]
@Le-zOU That's a direct link, it should work on v4
