### ISSUE TITLE
imx.to links are not always showing the "continue" page and vripper is confused

### ISSUE THREAD

**Issue by CaptnSeraph** [death-claw/vripper-project#67]
```Failed to download https://imx.to/u/i/2022/03/27/30fji1.jpg
 tn.mnlr.vripper.exception.DownloadException: tn.mnlr.vripper.exception.HostException: //*[@name='imgContinue'] cannot be found
	at tn.mnlr.vripper.download.DownloadJob.download(DownloadJob.java:172)
	at tn.mnlr.vripper.download.DownloadJob.run(DownloadJob.java:253)
	at net.jodah.failsafe.Functions.lambda$supplierOf$12(Functions.java:296)
	at net.jodah.failsafe.Functions.lambda$resultSupplierOf$11(Functions.java:283)
	at net.jodah.failsafe.internal.executor.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:67)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:117)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:319)
	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:219)
	at tn.mnlr.vripper.download.DownloadJobWrapper.run(DownloadJobWrapper.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: tn.mnlr.vripper.exception.HostException: //*[@name='imgContinue'] cannot be found
	at tn.mnlr.vripper.host.ImxHost.getNameAndUrl(ImxHost.java:77)
	at tn.mnlr.vripper.download.DownloadJob.download(DownloadJob.java:101)
	... 11 more
```

Ill poke at the logic and see if i can recommend a solution

**Comment by mearachdmor** [comment]
It's just returning the file.  So cheap dirty fix by changing ImxHost.java line 77.

//throw new HostException(CONTINUE_BUTTON_XPATH + " cannot be found" );
return new HostService.NameUrl(_url, _url);

**Comment by kalebkan360** [comment]
Please, where we can edit the fix? where is the  ImxHost.java file? I work with linux version of the program.
thanks
