### ISSUE TITLE
Thinks all posts are multiposts and won't download.

### ISSUE THREAD

**Issue by runchbox** [death-claw/vripper-project#68]
Can't copypaste but this is most of the error it's giving me:

https://puu.sh/J0gVO/098960f415.png

**Comment by artvand** [comment]
I'm getting the same error, even if I copy the link of a single post (it doesn't think it's a multipost, but still has that 403 code). Just started today.

Error when adding gallery https://vipergirls.to/threads/7014791?p=105921146
net.jodah.failsafe.FailsafeException: tn.mnlr.vripper.exception.DownloadException: Unexpected response code '403' for GET https://vipergirls.to/vr.php?p=105921146 HTTP/1.1
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:323)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:71)
	at tn.mnlr.vripper.services.domain.PostScanParser.getPost(PostScanParser.java:68)
	at tn.mnlr.vripper.services.domain.PostScanParser.parse(PostScanParser.java:55)
	at tn.mnlr.vripper.tasks.AddPostRunnable.run(AddPostRunnable.java:80)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: tn.mnlr.vripper.exception.DownloadException: Unexpected response code '403' for GET https://vipergirls.to/vr.php?p=105921146 HTTP/1.1
	at tn.mnlr.vripper.services.domain.PostScanParser.lambda$getPost$1(PostScanParser.java:75)
	at net.jodah.failsafe.Functions.lambda$resultSupplierOf$11(Functions.java:283)
	at net.jodah.failsafe.internal.executor.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:67)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:117)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:319)
	... 9 more

**Comment by PsychoSid** [comment]
fwiw I am getting this as well.

**Comment by raggabrashtrout** [comment]
I'm getting the same error
Sometimes when accessing VG from a browser it dose a "cloudflare verification"
I'm wondering if vripper isn't getting passed this

**Comment by HudsonW735** [comment]
We all has that problem. Maybe it's the end of vripper?

**Comment by PsychoSid** [comment]
This should be OK now the Cloudflare protection period has expired.

**Comment by HudsonW735** [comment]
My life has sense again! THX
