### ISSUE TITLE
cant' download from imx.to when format link directly images

### ISSUE THREAD

**Issue by kalebkan360** [death-claw/vripper-project#85]
I find an issue downloading from imx.to with vripper 3.5.4 for Linux when format is: imx.to/u/i/2022/10/24/*.jpg. It seems that the issue is in the format acceptance. When downloading from the same site, in a simple  format as imx.to/i/[dir] no issues are detected.

Failed to download etc
 tn.mnlr.vripper.exception.DownloadException: tn.mnlr.vripper.exception.HostException: //*[@name='imgContinue'] cannot be found
	at tn.mnlr.vripper.download.DownloadJob.download(DownloadJob.java:172)
	at tn.mnlr.vripper.download.DownloadJob.run(DownloadJob.java:253)
	at net.jodah.failsafe.Functions.lambda$supplierOf$12(Functions.java:296)
	at net.jodah.failsafe.Functions.lambda$resultSupplierOf$11(Functions.java:283)
	at net.jodah.failsafe.internal.executor.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:67)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:117)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:319)
	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:219)
	at tn.mnlr.vripper.download.DownloadJobWrapper.run(DownloadJobWrapper.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: tn.mnlr.vripper.exception.HostException: //*[@name='imgContinue'] cannot be found
	at tn.mnlr.vripper.host.ImxHost.getNameAndUrl(ImxHost.java:77)
	at tn.mnlr.vripper.download.DownloadJob.download(DownloadJob.java:101)
	... 11 more

Is there kindly a possible solution?

**Comment by death-claw** [comment]
Try latest version v4.x.x
